<?php
$title = "FAQs";
include "header.php"?>
<p>Here I'll post some answers to certain FAQs.</p>

<div>
  <h2>What do you use to produce your notes?</h2>
  <p>The notes themselves are typset in LaTeX, and most diagrams are drawn with TikZ. As of the time of writing, exactly two plots are generated by Mathematica and one is from Wikimedia Commons (all of which are used in IA Differential Equations).</p>

  <p>To type the notes, I just use some text editor (not saying which, to avoid causing controversy), and use the TeX Live distribution to compile the files. I tend to use mupdf to view the pdfs. Everything is version-controlled with <code>git</code> and hosted on <a href="https://github.com/dalcde/cam-notes">GitHub</a>.</p>

  <p>All of these are run on a linux system, and everything is installed via the package manager (in particular, don't ask me how to install <code>$SOFTWARE</code> on Windows/OS X, since I have completely no idea).</p>
</div>

<div>
  <h2>What else do you use to produce your notes?</h2>
  <p>I have a handful of helper scripts in my "build system":</p>
  <ul>
    <li><code>gen.sh</code> does the compilation and generates the various different versions of my notes.</li>
    <li><code>sync.sh</code> is used to send the files to the SRCF server hosting this site.</li>
    <li><code>test.sh</code> goes through the source file and looks for certain common errors and things that don't conform to some arbitrary style guide I've set myself.</li>
    <li><code>clean.sh</code> fixes certain simple errors like trailing whitespaces. </li>
    <li><code>sync-mirror.sh</code> updates the GitHub mirror.</li>
    <li><code>count.sh</code> computes the page/line/word/character count.</li>
  </ul>
</div>

<?php
    $result = file_get_contents("/home/dec41/.note-count");
    if ($result) {
    ?>
<div>
  <h2>How much stuff have you got here?</h2>
  <p>There are currently</p>
  <ul>
<?php
        $eresult = explode("\n", $result);
        $pages = $eresult[0];
        $lines = $eresult[1];
        $words = $eresult[2];
        $characters = $eresult[3];

        echo "    <li>$pages pages of notes;</li>\n";
        echo "    <li>$lines lines of source code;</li>\n";
        echo "    <li>$words words in the source code; and</li>\n";
        echo "    <li>$characters characters in the source code.</li>\n";
?>
  </ul>
</div>
<?php
    }
?>
<div>
  <h2>How do I compile the tex files?</h2>
  <p>I assume you already have the appropriate compiler and packages installed (see question 1). The list of all packages needed can be found in <a href="/notes/header.tex"><code>header.tex</code></a>.</p>

  <p>The recommended way to compile the source file is to download the source (labeled &quot;src&quot;) from the <a href="/">notes page</a> together with <a href="/notes/header.tex"><code>header.tex</code></a>. <em>Put them in the same folder</em>, and then compile the source file with your compiler. For the notes with images, you have to download the images from the <a href="https://github.com/dalcde/cam-notes">GitHub repository</a> and place them in a folder named <code>image</code>.</p>

  <p>Alternatively, you can clone the GitHub repository by running <code>git clone <a href="https://github.com/dalcde/cam-notes">https://github.com/dalcde/cam-notes</a></code>. Then you can just navigate to the appropriate folder and compile. Note that the <code>header.tex</code> is stored at the root folder and symlinked to every subfolder. Windows does not like this (technically, anything that is on an FAT or NTFS filesystem). You will have to manually replace the <code>header.tex</code> in each subdirectory to the actual <code>header.tex</code>.</p>
</div>
<?php include "footer.php"?>
