<?php
$title = "Maths Lecture Notes";
include "header.php"?>

<p>Below are the notes I took during lectures in Cambridge. None of this is official (unless otherwise specified). Included as well are stripped-down versions (eg. definition-only; script-generated and doesn't necessarily make sense), example sheets, and the source code. The source code has to be compiled with <a href="notes/header.tex"><code>header.tex</code></a>, and is also available on <a href="http://github.com/dalcde/cam-notes">GitHub</a>.</p>
<?php #<p>Unready notes are <span class="notes-item notes-item-old">greyed out</span>.</p>?>

<p>Note that the lecture notes are not reliable indicators for what was lectured in my year, or what will be lectured in your year, as I tend to change, add and remove contents from the notes after the lectures occur.</p>

<p>The notes for the courses in the current term will not be available until the term ends. See <a href="/taken_down">here</a> for more details. Please email me (or use other methods to contact me) if you want to obtain a copy of the relevant notes for legitimate purposes..</p>

<?php include "courses_list.php"; ?>

<section>
<h1>Stuff</h1>
<p>THESE NOTES ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, LACK OF TYPOS AND FUNNINESS OF PUNS.</p>

<p>Nevertheless, please email any comments to <a href="mailto:dec41@cam.ac.uk">dec41@cam.ac.uk</a>. Feel free to point out errors or unclear explanations, as well as general typographic suggestions. Even better, send a GitHub <a href="http://github.com/dalcde/cam-notes/pulls">pull request</a>.</p>

<p>Here I'd like to thank the lecturers who delivered the (usually) amazing lectures, and all of those who helpfully pointed out my mistakes and typos.</p>

<p>Usual disclaimer: The notes have been continuously modified since the lectures have taken place, and do not necessarily accurately reflect what the lecturer said or thought. In particular, all errors are (almost certainly) mine.</p>

</section>
<section>
<h1>External resources</h1>
<p>Notes from other sources I like.</p>
<ul>
  <li><a href="http://tartarus.org/gareth/maths/notes/">Gareth Taylor's</a> notes. Mostly pure mathematics.</a></li>
  <li><a href="http://www.damtp.cam.ac.uk/user/tong/teaching.html">David Tong's</a> notes. Theoretical physics.</a></li>
  <li><a href="http://www.statslab.cam.ac.uk/~rrw1/">Richard Weber's</a> notes. Applicable courses.</li>
  <li><a href="http://www.archim.org.uk/notes.php">Archimedeans'</a> site. Miscellaneous topics from different sources.</a></li>
  <li><a href="https://www.maths.cam.ac.uk/tripos-specific-resources">Student Representatives'</a> page. Miscellaneous topics from different sources. May overlap with above.</a></li>
</ul>
</section>

<section>
<h1>(Not so) frequently asked questions</h1>
<section>
  <h2>What do you use to produce your notes?</h2>
  <p>The notes themselves are typset in LaTeX, and most diagrams are drawn with TikZ. As of the time of writing, exactly two plots are generated by Mathematica and one is from Wikimedia Commons (all of which are used in IA Differential Equations).</p>

  <p>To type the notes, I just use some text editor (not saying which, to avoid causing controversy), and use the TeX Live distribution to compile the files. I tend to use mupdf to view the pdfs. Everything is version-controlled with <code>git</code> and hosted on <a href="https://github.com/dalcde/cam-notes">GitHub</a>.</p>

  <p>All of these are run on a linux system, and everything is installed via the package manager (in particular, don't ask me how to install <code>$SOFTWARE</code> on Windows/OS X, since I have completely no idea).</p>
</section>

<section>
  <h2>What else do you use to produce your notes?</h2>
  <p>I have a handful of helper scripts in my "build system":</p>
  <ul>
    <li><code>gen.sh</code> does the compilation and generates the various different versions of my notes.</li>
    <li><code>sync.sh</code> is used to send the files to the SRCF server hosting this site.</li>
    <li><code>test.sh</code> goes through the source file and looks for certain common errors and things that don't conform to some arbitrary style guide I've set myself.</li>
    <li><code>clean.sh</code> fixes certain simple errors like trailing whitespaces. </li>
    <li><code>sync-mirror.sh</code> updates the GitHub mirror.</li>
    <li><code>count.sh</code> computes the page/line/word/character count.</li>
  </ul>
</section>

<?php
    $result = file_get_contents("/home/dec41/.note-count");
    if ($result) {
    ?>
<section>
  <h2>How much stuff have you got here?</h2>
  <p>There are currently</p>
  <ul>
<?php
        $eresult = explode("\n", $result);
        $pages = $eresult[0];
        $lines = $eresult[1];
        $words = $eresult[2];
        $characters = $eresult[3];

        echo "    <li>$pages pages of notes;</li>\n";
        echo "    <li>$lines lines of source code;</li>\n";
        echo "    <li>$words words in the source code; and</li>\n";
        echo "    <li>$characters characters in the source code.</li>\n";
?>
  </ul>
</section>
<?php
    }
?>
<section>
  <h2>How do I compile the tex files?</h2>
  <p>I assume you already have the appropriate compiler and packages installed (see question 1). The list of all packages needed can be found in <a href="/notes/header.tex"><code>header.tex</code></a>.</p>

  <p>The recommended way to compile the source file is to download the source (labeled &quot;src&quot;) from the <a href="/">notes page</a> together with <a href="/notes/header.tex"><code>header.tex</code></a>. <em>Put them in the same folder</em>, and then compile the source file with your compiler. For the notes with images, you have to download the images from the <a href="https://github.com/dalcde/cam-notes">GitHub repository</a> and place them in a folder named <code>image</code>.</p>

  <p>Alternatively, you can clone the GitHub repository by running <code>git clone <a href="https://github.com/dalcde/cam-notes">https://github.com/dalcde/cam-notes</a></code>. Then you can just navigate to the appropriate folder and compile. Note that the <code>header.tex</code> is stored at the root folder and symlinked to every subfolder. Windows does not like this (technically, anything that is on an FAT or NTFS filesystem). You will have to manually replace the <code>header.tex</code> in each subdirectory to the actual <code>header.tex</code>.</p>
</section>

</section>
<?php include "footer.php"?>
